const OpenAI = require("openai");

// Initialize OpenAI only if key is present
let openai;
if (process.env.OPENAI_API_KEY) {
    openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
} else {
    console.warn("OPENAI_API_KEY not found in environment variables. Using MOCK LLM.");
}

const rewriteArticle = async (originalArticle, sourceContents) => {
    try {
        if (!openai) {
            return mockRewrite(originalArticle, sourceContents);
        }

        const prompt = `
        You are an expert content writer/editor.
        
        Original Article Title: "${originalArticle.title}"
        Original Content: "${originalArticle.content.substring(0, 1000)}..."
        
        I have found two related articles from Google Search:
        
        Source 1:
        "${sourceContents[0] ? sourceContents[0].substring(0, 1000) : "N/A"}..."
        
        Source 2:
        "${sourceContents[1] ? sourceContents[1].substring(0, 1000) : "N/A"}..."
        
        Task:
        Rewrite the original article to make it more comprehensive, using insights from the two source articles.
        The new article must be similar in formatting to the top ranking articles (the sources).
        
        IMPORTANT:
        - Maintain the original core message but enhance it.
        - At the very bottom of the article, add a section called "References" and list the URLs of the two source articles.
        - Return ONLY the new article content (Markdown format is preferred).
        `;

        const completion = await openai.chat.completions.create({
            messages: [{ role: "user", content: prompt }],
            model: "gpt-3.5-turbo",
        });

        return completion.choices[0].message.content;

    } catch (error) {
        console.error("LLM Error:", error);
        return originalArticle.content + "\n\n(LLM Enhancement Failed: " + error.message + ")";
    }
};

const mockRewrite = (originalArticle, sourceContents) => {
    console.log("Mock LLM: Rewriting article...");
    // Simple dummy rewrite for testing without API key
    let newContent = `
# [UPDATED] ${originalArticle.title}

(This is a AI-enhanced version of the article generated by a Mock LLM Service because no API Key was provided.)

${originalArticle.content}

## Additional Insights
Here are some insights derived from external sources:
- From Source 1: The topic is widely discussed...
- From Source 2: Experts agree that...

## References
1. External Source 1 (Scraped)
2. External Source 2 (Scraped)
    `;
    return newContent;
};

module.exports = { rewriteArticle };
